title: polictf
email: info@polictf.it
description: >- # this means to ignore newlines until "baseurl:"
   polictf is an online jeopardy-style capture the flag competition, organized
   with love by the Tower of Hanoi CTF team and open to everyone!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

